### ISSUE TITLE
Triage Service exceptions: Cannot find fields enabled for suggestions. Provide 'suggesterName' in query. (/definitions)

### ISSUE THREAD

**Issue by grvillic** [clearlydefined/operations#35]
This is returning a 400 internally, but clients are getting a 500.

```
requests 
| where resultCode == 500
| join (
 exceptions
 ) on operation_Id 
| extend pathPrefix = extract("/(\\w+)", 0, tostring(operation_Name))
| summarize count() by  outerMessage, pathPrefix
| order by count_  desc 
| where outerMessage contains "Cannot find fields enabled for suggestions" 
```

**Comment by jcfiorenzano** [comment]
This is happening if the search pattern includes the encoding %23 and IIS is interpreting that as a fragment ignoring the rest of the url parameters like suggesterName. I created a support item for Azure Search because this looks like an issue in their end.

**Comment by nellshamrell** [comment]
Hey @jcfiorenzano - did you ever hear back from Azure Support on this?
